name: PRAutoTest
on:
  pull_request:
    paths:
      - 'src/test/*_exp.sol'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # Required to fetch all branches

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Format
        run: forge fmt
        id: fmt

      - name: Build
        run: forge build
        id: build

      - name: Run Forge tests
        run: |
          shopt -s nullglob
          base_sha=${{ github.event.pull_request.base.sha }}
          head_sha=${{ github.event.pull_request.head.sha }}
          changed_files=$(git diff --name-only $base_sha $head_sha)
          for file in $changed_files; do
            if [[ $file == src/test/*_exp.sol ]]; then
              forge test --contracts "$file" -vvv
            fi
          done
        id: test
